export const GET_ALL_JOBS = "GET_ALL_JOBS";
export const GET_ALL_APPLICATION = "GET_ALL_APPLICATION";
export const CREATE_EMPLOYER = "CREATE_EMPLOYER";

export const CREATE_ASPIRANT = "CREATE_ASPIRANT";
export const GET_ORGANIZATION = "GET_ORGANIZATION";

export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const CURRENT_USER = "CURRENT_USER";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const LOGINTABIDX = "LOGINTABIDX";

export const SELECT_JOB_ID = "SELECT_JOB_ID";
export const ALL_ASPIRANT = "ALL_ASPIRANT";
export const ASPIRANT = "ASPIRANT";
export const EMPLOYER = "EMPLOYER";
